-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 14:54:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BOOKVAULT` DEFAULT CHARACTER SET utf8 ;
USE `BOOKVAULT` ;

-- -----------------------------------------------------
-- Table `mydb`.`ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKVAULT`.`ADMINISTRADOR` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `correo` VARCHAR(30) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKVAULT`.`USUARIO` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `primer_apellido` VARCHAR(15) NOT NULL,
  `segundo_apellido` VARCHAR(15) NULL,
  `edad` INT NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(30) NOT NULL,
  `intereses` VARCHAR(50) NOT NULL,
  `semestre` INT NOT NULL,
  `ADMINISTRADOR_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_USUARIO_ADMINISTRADOR1_idx` (`ADMINISTRADOR_idAdmin` ASC),
  CONSTRAINT `fk_USUARIO_ADMINISTRADOR1`
    FOREIGN KEY (`ADMINISTRADOR_idAdmin`)
    REFERENCES `mydb`.`ADMINISTRADOR` (`idAdmin`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LIBRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKVAULT`.`LIBRO` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `ISBN` VARCHAR(13) NOT NULL,
  `nombreAutor` VARCHAR(20) NOT NULL,
  `apellidosAutor` VARCHAR(20) NOT NULL,
  `edicion` INT NOT NULL,
  `cantidadPaginas` INT NOT NULL,
  `titulo` VARCHAR(30) NOT NULL,
  `ciudad` VARCHAR(20) NOT NULL,
  `editorial` VARCHAR(20) NOT NULL,
  `genero` VARCHAR(30) NULL,
  `yearEdicion` INT NOT NULL,
  `ADMINISTRADOR_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idLibro`),
  INDEX `fk_LIBRO_ADMINISTRADOR1_idx` (`ADMINISTRADOR_idAdmin` ASC),
  CONSTRAINT `fk_LIBRO_ADMINISTRADOR1`
    FOREIGN KEY (`ADMINISTRADOR_idAdmin`)
    REFERENCES `mydb`.`ADMINISTRADOR` (`idAdmin`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAVORITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKVAULT`.`FAVORITO` (
  `idFavorito` INT NOT NULL AUTO_INCREMENT,
  `nombreAutor` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `tituloLibro` VARCHAR(30) NOT NULL,
  `USUARIO_idUsuario` INT NOT NULL,
  `LIBRO_idLibro` INT NOT NULL,
  PRIMARY KEY (`idFavorito`, `USUARIO_idUsuario`, `LIBRO_idLibro`),
  INDEX `fk_FAVORITO_USUARIO_idx` (`USUARIO_idUsuario` ASC),
  INDEX `fk_FAVORITO_LIBRO1_idx` (`LIBRO_idLibro` ASC),
  CONSTRAINT `fk_FAVORITO_USUARIO`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`USUARIO` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FAVORITO_LIBRO1`
    FOREIGN KEY (`LIBRO_idLibro`)
    REFERENCES `mydb`.`LIBRO` (`idLibro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
